### ISSUE TITLE
Define clear and orderly file structure

### ISSUE THREAD

**Issue by HerrX2000** [callidaria/pen-testing#12]
Current package structure is messy and inconsistent, we need to improve that.

**Comment by HerrX2000** [comment]
#18 comes with my new proposal for our file structure
data/

    xml
    sqlit

source/

    controller/
    database/
    model/
    view/

**Comment by callidaria** [comment]
+1

**Comment by callidaria** [comment]
Not anymore in branch cld/develop. Go, Check it out, BE INSPIRED by this beauty!

**Comment by HerrX2000** [comment]
I've checked out your branch. Well you just deleted all of the sql stuff 😄 I'd advocate for keeping them as backup. But keeping sql as backup is up to debat, but what you can't do is just remove all of the project config files.

Their needs to be a project wide gitignore, classpath, and eclipse project config.

**Comment by callidaria** [comment]
why do we need the eclipse stuff? we can just import this from our cloned directory
