### ISSUE TITLE
Writing XML API

### ISSUE THREAD

**Issue by HerrX2000** [callidaria/pen-testing#19]
Writing operations on our XML database.

**Comment by HerrX2000** [comment]
#18 comes with a basic reading API for XML

**Comment by callidaria** [comment]
Done?

**Comment by HerrX2000** [comment]
Writing on XML is planed for a later alpha stage. Because our "costumers" might have weird requirments.

**Comment by callidaria** [comment]
No that won't happen! I can't imagine!

**Comment by HerrX2000** [comment]
Writing XML API alpha level is finished.
These are the supported public methodes:

addInventoryEntry(InventoryEntry)
replaceInventoryEntry(int, InventoryEntry)
replaceInventoryEntry(int, InventoryEntry, Boolean)
editAttributeOfInventoryEntry(int, String, String)
deleteInventoryEntry(int, Boolean)
validate()
nameExists(String)
uidExists(int)
escapeString(String)

**Comment by HerrX2000** [comment]
This issue is closed, I will open a different issue for refinements.
