### ISSUE TITLE
Define our model (basic classes)

### ISSUE THREAD

**Issue by HerrX2000** [callidaria/pen-testing#20]
Our model package must includes all basic classes like following:

InventoryEntry
Product
Category
(Names are due to change)

The model is visualized in the "UML Klassendiagram" including all attributes and methodes.

**Comment by HerrX2000** [comment]
Setter will directly write to our database via the Database API

**Comment by HerrX2000** [comment]
@callidaria are we missing any basic classes? If not, this issue can be closed.

**Comment by callidaria** [comment]
If i need any, i'll contact you!
