### ISSUE TITLE
UML class diagram for Controller

### ISSUE THREAD

**Issue by HerrX2000** [callidaria/pen-testing#26]
The UML Classdiagram for the controller can be done in advance or after the prototyp of the controller is done.

**Comment by callidaria** [comment]
I'm doing it my way and Lukas gets a .txt documentation

**Comment by HerrX2000** [comment]
Sounds good to me.

**Comment by HerrX2000** [comment]
I will work out an Interface for the controller in the next week after they announce the 3rd assignment.
