### ISSUE TITLE
Database set up

### ISSUE THREAD

**Issue by HerrX2000** [callidaria/pen-testing#5]
Getting the MySQL Server up and running.

**Comment by HerrX2000** [comment]
We are having problems with setting up the server across multiple developer and OSs.

**Comment by HerrX2000** [comment]
We are probalby moving to SQLite see #9

**Comment by callidaria** [comment]
Wasn't so hard actually

**Comment by HerrX2000** [comment]
Moved to SQLite
We now don't need a server anymore. SQLite database can be pushed to git as well and work crossplatform.

**Comment by HerrX2000** [comment]
SQLite is love and life. Closed for now. Reopen if we ever migrate to MySQL
